[project]
name = "a2a-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "a2a-sdk>=0.3.8",
    "flask>=3.1.2",
    "google-adk>=1.13.0",
    "google-generativeai>=0.8.5",
    "starlette>=0.48.0",
]
